create table public.companies (
  id bigint generated by default as identity not null,
  name text not null,
  description text null,
  contact_email text not null,
  contact_phone text null,
  created_at timestamp with time zone not null default now(),
  constraint companies_pkey primary key (id)
) TABLESPACE pg_default;