create table public.jobs (
  id bigint generated by default as identity not null,
  title text not null,
  type text not null,
  description text null,
  salary text not null,
  location text not null,
  created_at timestamp with time zone not null default now(),
  company_id bigint not null,
  constraint jobs_pkey primary key (id),
  constraint jobs_company_id_fkey foreign KEY (company_id) references companies (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;